export const GET_CATEGORIAS = 'GET_CATEGORIAS'
export const GET_MEDIATYPE = 'GET_MEDIATYPE'
export const GET_MEDIAURL = 'GET_MEDIAURL'
export const NEXT_VISOR = 'CURRENT_VISOR'
export const RESET_VISOR = 'RESET_VISOR'
export const RESET_MEDIA = 'RESET_MEDIA'
export const GET_POSTS = 'GET_POSTS'
export const GET_INFO = 'GET_INFO'